# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/TronApp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12misc/TronApp.proto\"\xb6\x01\n\x0f\x45xchangeDetails\x12\x12\n\nexchangeId\x18\x01 \x01(\x04\x12\x10\n\x08token1Id\x18\x02 \x01(\t\x12\x12\n\ntoken1Name\x18\x03 \x01(\t\x12\x17\n\x0ftoken1Precision\x18\x04 \x01(\r\x12\x10\n\x08token2Id\x18\x05 \x01(\t\x12\x12\n\ntoken2Name\x18\x06 \x01(\t\x12\x17\n\x0ftoken2Precision\x18\x07 \x01(\r\x12\x11\n\tsignature\x18\x08 \x01(\x0c\"B\n\x0cTokenDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tprecision\x18\x02 \x01(\r\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'misc.TronApp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXCHANGEDETAILS._serialized_start=23
  _EXCHANGEDETAILS._serialized_end=205
  _TOKENDETAILS._serialized_start=207
  _TOKENDETAILS._serialized_end=273
# @@protoc_insertion_point(module_scope)
